[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
itertools = "0.14.0"
nom = "7.1.3"
num-traits = "0.2.19"
reqwest = "0.12.12"
tokio = {version = "1.42.0", features = ["full"]}
